name: Docker image experiment

on:
  push:

jobs:
  dockerbasedci:
    name: build-inside-docker
    runs-on: ubuntu-latest
    #container: conanio/gcc9:latest

    steps:
      - uses: actions/checkout@v1
      - name: make-build-dir
        run: mkdir build
      - name: cmake-configure-debug
        run: cmake -DCMAKE_BUILD_TYPE=Debug ..
        working-directory: ./build
      - name: build-debug
        run: cmake --build ./build --config Debug
      - name: ctest
        run: ctest -C Debug
        working-directory: ./build
