name: Docker image experiment

on:
  push:

jobs:
  dockerbasedci:
    name: build-inside-docker
    runs-on: ubuntu-latest
    container:
      image: conanio/gcc9:latest

    steps:
      - uses: actions/checkout@v1
      - name: finding-source in root
        run: pwd && ls
      # - name: cmake-configure-debug
      #   run: cmake -DCMAKE_BUILD_TYPE=Debug ..
      #   working-directory: /root/mount/build
      # - name: build-debug
      #   run: cmake --build . --config Debug
      #   working-directory: /root/mount/build
      # - name: ctest
      #   run: ctest -C Debug
      #   working-directory: /root/mount/build
